apiVersion: v1
kind: Service
metadata:
  name: object-detection
spec:
  type: NodePort
  selector:
    app: object-dectection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30125
